/* SPDX-License-Identifier: MIT
 *
 * Copyright (C) 2019-2026 WireGuard LLC. All Rights Reserved.
 */

package conf

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const DNSCryptConfigSuffix = ".dnscrypt.json"

type DNSCryptConfig struct {
	Enabled       bool   `json:"enabled"`
	ListenAddress string `json:"listen_address"`
	ServerNames   string `json:"server_names"`
	CustomTOML    string `json:"custom_toml"`
}

func DefaultDNSCryptConfig() *DNSCryptConfig {
	return &DNSCryptConfig{
		Enabled:       false,
		ListenAddress: "127.0.0.1:53",
		ServerNames:   "",
		CustomTOML:    "",
	}
}

func LoadDNSCryptConfig(tunnelName string) (*DNSCryptConfig, error) {
	if !TunnelNameIsValid(tunnelName) {
		return nil, os.ErrNotExist
	}
	configFileDir, err := tunnelConfigurationsDirectory()
	if err != nil {
		return nil, err
	}
	path := filepath.Join(configFileDir, tunnelName+DNSCryptConfigSuffix)
	bytes, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var cfg DNSCryptConfig
	err = json.Unmarshal(bytes, &cfg)
	if err != nil {
		return nil, err
	}
	return &cfg, nil
}

func (cfg *DNSCryptConfig) Save(tunnelName string) error {
	if !TunnelNameIsValid(tunnelName) {
		return os.ErrInvalid
	}
	configFileDir, err := tunnelConfigurationsDirectory()
	if err != nil {
		return err
	}
	path := filepath.Join(configFileDir, tunnelName+DNSCryptConfigSuffix)
	bytes, err := json.MarshalIndent(cfg, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, bytes, 0o600)
}

func DeleteDNSCryptConfig(tunnelName string) error {
	if !TunnelNameIsValid(tunnelName) {
		return os.ErrInvalid
	}
	configFileDir, err := tunnelConfigurationsDirectory()
	if err != nil {
		return err
	}
	path := filepath.Join(configFileDir, tunnelName+DNSCryptConfigSuffix)
	return os.Remove(path)
}

// GenerateTOML generates a dnscrypt-proxy.toml file content.
// If CustomTOML is non-empty, it is used directly.
// Otherwise, a minimal configuration is generated from ListenAddress and ServerNames.
func (cfg *DNSCryptConfig) GenerateTOML() string {
	if strings.TrimSpace(cfg.CustomTOML) != "" {
		return cfg.CustomTOML
	}

	listenAddr := cfg.ListenAddress
	if listenAddr == "" {
		listenAddr = "127.0.0.1:53"
	}

	var b strings.Builder
	b.WriteString("## Generated by WireGuard for Windows with DNSCrypt support\n\n")
	b.WriteString(fmt.Sprintf("listen_addresses = ['%s']\n\n", listenAddr))
	b.WriteString("max_clients = 250\n")
	b.WriteString("ipv4_servers = true\n")
	b.WriteString("ipv6_servers = false\n")
	b.WriteString("dnscrypt_servers = true\n")
	b.WriteString("doh_servers = true\n")
	b.WriteString("odoh_servers = false\n")
	b.WriteString("require_dnssec = false\n")
	b.WriteString("require_nolog = true\n")
	b.WriteString("require_nofilter = true\n")
	b.WriteString("disabled_server_names = []\n\n")

	if strings.TrimSpace(cfg.ServerNames) != "" {
		names := strings.Split(cfg.ServerNames, ",")
		var quoted []string
		for _, n := range names {
			n = strings.TrimSpace(n)
			if n != "" {
				quoted = append(quoted, fmt.Sprintf("'%s'", n))
			}
		}
		if len(quoted) > 0 {
			b.WriteString(fmt.Sprintf("server_names = [%s]\n\n", strings.Join(quoted, ", ")))
		}
	}

	b.WriteString("[sources.public-resolvers]\n")
	b.WriteString("urls = [\n")
	b.WriteString("  'https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/public-resolvers.md',\n")
	b.WriteString("  'https://download.dnscrypt.info/resolvers-list/v3/public-resolvers.md',\n")
	b.WriteString("]\n")
	b.WriteString("cache_file = 'public-resolvers.md'\n")
	b.WriteString("minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'\n")
	b.WriteString("refresh_delay = 73\n")
	b.WriteString("prefix = ''\n")

	return b.String()
}
